### ISSUE TITLE
Consider adding a note in docs about pinning version of `TranscodingStreams`

### ISSUE THREAD

**Issue by neelsmith** [bauglir/Kroki.jl#45]
Since current versions of `TranscodingStreams` throw an error when invoked by Kroki, it would be helpful to Kroki users to be alerted to this, since the work around is as easy as pinning the version of `TranscodingStreams` to 0.9.11.

A note on the README and in the ghpages documentation would have saved me a little time and frustration, and prevented me from filing an issue here when the real bug is in TranscodingStreams.

**Comment by bauglir** [comment]
Unfortunately, I didn't expect the fix to take as long to land in a release as it did. Otherwise, a note like this would indeed have been useful. I'm sorry for the confusion. The underlying issue has been addressed in JuliaIO/TranscodingStreams.jl#141 and released through [`TranscodingStreams@0.9.13`](https://github.com/JuliaIO/TranscodingStreams.jl/releases/tag/v0.9.13).

In general, I prefer not to work around issues in dependencies unless strictly necessary and this seemed like an easy fix. But I will keep this in mind for the future. Thanks for your feedback.
